### ISSUE TITLE
role の削除とサポート OS の変更

### ISSUE THREAD

**Issue by rinatz** [rinatz/playbooks#9]
@sou-hayashi @Raita876 @ajitsuki 

自分がもう使用しない role やサポート OS を削除したいです。
継続利用する場合は fork してもらったほうがいいかも。

**Comment by sou-hayashi** [comment]
ご連絡いただきありがとうございます。
今後は fork したものを利用させていただきます。

**Comment by rinatz** [comment]
@sou-hayashi 
ありがとうございます。
fork を最新のコミットに同期したら issue をクローズします。

**Comment by sou-hayashi** [comment]
@rinatz 
最新のコミットへ同期済みです 🙇
